name: Check docs
description: Fail the job if README.md is not present at the repo root.

runs:
  using: composite
  steps:
    - name: Verify README.md presence
      shell: bash
      run: |
        [ -f README.md ] || (printf '%b\n' "${CI_TEXT_RED}A README.md file must be present at project root${CI_TEXT_CLEAR}" && exit 1)
        printf '%b\n' "${CI_TEXT_GREEN}README.md present${CI_TEXT_CLEAR}"
